"""
sgx_listed_companies.py
=======================

A bundled, OFFLINE reference list of SGX-listed company names, used to
provide supporting evidence when a user claims the 'SGX-listed' RORC
exemption category (Section 6 of the PRD, category 1).

IMPORTANT - this list is INDICATIVE ONLY, derived from a public Wikipedia
snapshot (data as of approximately December 2020) and is NOT guaranteed to
be current or complete. Companies may have been added, delisted, or renamed
since. This is suitable for demo purposes to show how a name-matching check
would work, but production use should replace this with a live feed from
SGX or an official/licensed data source.

Source last checked: June 2026 (list data itself dated ~December 2020).
"""

SGX_LISTED_COMPANIES = [
    '8Telecom International Holdings Co Ltd',
    'A-Smart Holdings Ltd',
    'A-Sonic Aerospace Limited',
    'ABF Singapore Bond Index Fund',
    'ABR Holdings Limited',
    'Abterra Ltd',
    'Accordia Golf Trust',
    'Ace Achieve Infocom Limited',
    'Achieva Limited',
    'Acma Ltd',
    'Addvalue Technologies Ltd',
    'Advanced Holdings Ltd',
    'Advanced Integrated Manufacturing Corp. Ltd.',
    'AEI Corporation Ltd',
    'AEM Holdings Ltd',
    'AF Global Limited',
    'AIMS APAC REIT',
    'AIMS Property Securities Fund',
    'Alibaba Pictures Group Limited',
    'Allied Technologies Limited',
    'Amara Holdings Limited',
    'Amcorp Global Limited',
    'AMOS Group Limited',
    'AMTD International Inc',
    'AnAn International Limited',
    'Anchun International Holdings Ltd',
    'AP Oil International Limited',
    'APAC Realty Limited',
    'ARA LOGOS Logistics Trust',
    'ARA US Hospitality Trust',
    'Ascendas India Trust',
    'Ascendas Real Estate Inv Trust',
    'Ascott Residence Trust',
    'Asia Enterprises Holding Limited',
    'Asia Fashion Holdings Limited',
    'Asian Pay Television Trust',
    'ASL Marine Holdings Ltd',
    'Aspial Corporation Limited',
    'Asti Holdings Limited',
    'AusGroup Limited',
    'Avarga Limited',
    'Avi-Tech Electronics Limited',
    'Azeus Systems Holdings Ltd',
    'Baker Technology Limited',
    'Ban Leong Technologies Limited',
    'Banyan Tree Holdings Limited',
    'BBR Holdings (S) Limited',
    'Beng Kuang Marine Limited',
    'Best World International Ltd',
    'BH Global Corporation Limited',
    'BHG Retail REIT',
    'Blumont Group Ltd',
    'BM Mobility Ltd',
    'Bonvests Holdings Limited',
    'Boustead Projects Limited',
    'Boustead Singapore Limited',
    'BRC Asia Limited',
    'British and Malayan Holdings Limited',
    'Broadway Industrial Group Limited',
    'Brook Crompton Holdings Ltd',
    'Bukit Sembawang Estates Limited',
    'Bumitama Agri Ltd',
    'Bund Center Investment Ltd',
    'Camsing Healthcare Limited',
    'CapitaLand Limited',
    'CapitaLand Integrated Commercial Trust',
    'CapitaLand Retail China Trust',
    'Captii Limited',
    'Casa Holdings Limited',
    'CDL Hospitality Trusts',
    'CDW Holding Limited',
    'CEI Limited',
    'Centillion Environment & Recycling Limited',
    'Centurion Corporation Limited',
    'CH Offshore Ltd',
    'Challenger Technologies Limited',
    'Chasen Holdings Limited',
    'Chemical Industries (Far East) Limited',
    'Cheng Mei Materials Technology Corporation',
    'Cheung Woh Technologies Ltd',
    'China Aviation Oil (Singapore) Corporation Ltd',
    'China Environment Ltd',
    'China Environmental Resources Group Limited',
    'China Everbright Water Limited',
    'China Fishery Group Limited',
    'China Great Land Holdings Ltd',
    'China Haida Ltd',
    'China Hongxing Sports Limited',
    'China International Holdings Limited',
    'China Jishan Holdings Limited',
    'China Kangda Food Company Ltd',
    'China Mining International Limited',
    'China Paper Holdings Limited',
    'China Sky Chemical Fibre Co Ltd',
    'China Sports International Limited',
    'China Sunsine Chemical Holdings Ltd',
    'China Taisan Technology Group Holdings Limited',
    'China Yuanbang Property Holdings Limited',
    'Chip Eng Seng Corporation Ltd',
    'Chuan Hup Holdings Ltd',
    'Citicode Ltd',
    'City Developments Limited',
    'Civmec',
    'Combine Will International Holdings Limited',
    'ComfortDelGro Corporation Limited',
    'Cordlife Group Limited',
    'Cortina Holdings Limited',
    'Cosco Shipping International (Singapore) Co Limited',
    'CosmoSteel Holdings Limited',
    'Courage Investment Group Limited',
    'Creative Technology Ltd',
    'Credit Bureau Asia Limited',
    'Cromwell European REIT',
    'CSC Holdings Limited',
    'CSE Global Ltd',
    'DFI Retail Group',
    'Darco Water Technologies',
    'Dasin Retail Trust',
    'Datapulse Technology',
    'DBS Group Holdings',
    'Debao Property Development',
    'Del Monte Pacific Limited',
    'Delfi Limited',
    'Design Studio Group Ltd',
    'Dragon Group International',
    'Dukang Distillers Hldgs',
    'Dutech Holdings',
    'Duty Free International',
    'Dyna-Mac Holdings',
    'Dynamic Colours',
    'Eagle Hospitality Trust',
    'EC World REIT',
    'Elec & Eltek International Company Limited',
    'Elite Commercial REIT',
    'Ellipsiz Ltd',
    'EMAS Offshore Limited',
    'Eneco Energy Limited',
    'Engro Corporation Limited',
    'Envictus International Holdings Limited',
    'Enviro-Hub Holdings Ltd',
    'ESR-REIT',
    'Excelpoint Technology Ltd',
    'Ezion Holdings Limited',
    'Ezra Holdings Limited',
    'F J Benjamin Holdings Ltd',
    'Fabchem China Limited',
    'Falcon Energy Group Limited',
    'Far East Hospitality Trust',
    'Far East Orchard Limited',
    'Federal International (2000) Ltd',
    'First Real Estate Investment Trust',
    'First Resources Limited',
    'First Ship Lease Trust',
    'First Sponsor Group Limited',
    'Food Empire Holdings Limited',
    'Forise International Limited',
    'Fragrance Group Limited',
    'Fraser and Neave Limited',
    'Frasers Centrepoint Trust',
    'Frasers Hospitality Trust',
    'Frasers Logistics & Commercial Trust',
    'Frasers Property Limited',
    'Frencken Group Limited',
    'Fu Yu Corporation Limited',
    'Full Apex (Holdings) Limited',
    'Fuxing China Group Limited',
    'Gallant Venture Ltd',
    'Genting Singapore Limited',
    'Geo Energy Resources Limited',
    'GK Goh Holdings Limited',
    'GL Limited',
    'Global Invacom Group Limited',
    'Global Investments Limited',
    'Global Palm Resources Holdings Limited',
    'Global Testing Corporation Limited',
    'Golden Agri-Resources Ltd',
    'Golden Energy and Resources Limited',
    'Goodland Group Limited',
    'GP Industries Limited',
    'Grand Banks Yachts Limited',
    'Great Eastern Holdings Ltd',
    'Green Build Technology Limited',
    'GRP Limited',
    'GSH Corporation Limited',
    'Guoan International Limited',
    'GuocoLand Limited',
    'GYP Properties Limited',
    'Hafary Holdings Limited',
    'Hai Leck Holdings Limited',
    'Halcyon Agri Corporation Limited',
    'Hanwell Holdings Limited',
    'Haw Par Corporation Limited',
    'Heeton Holdings Limited',
    'HG Metal Manufacturing Limited',
    'Hi-P International Limited',
    'Hiap Hoe Limited',
    'Hiap Seng Engineering Ltd',
    'HL Global Enterprises Limited',
    'Ho Bee Land Limited',
    'Hock Lian Seng Holdings Limited',
    'Hoe Leong Corporation Ltd',
    'Hong Fok Corporation Limited',
    'Hong Lai Huat Group Limited',
    'Hong Leong Asia Ltd',
    'Hong Leong Finance Limited',
    'Hongkong Land Holdings Limited',
    'Hor Kew Corporation Limited',
    'Hotel Grand Central Limited',
    'Hotel Properties Limited',
    'Hotel Royal Limited',
    'Hotung Investment Holdings Limited',
    'HRnetGroup Limited',
    'Hu An Cable Holdings Ltd',
    'Huan Hsin Holdings Ltd',
    'Hutchison Port Holdings Trust',
    'Hwa Hong Corporation Limited',
    'Hyflux Limited',
    'iFast Corporation Ltd',
    'IFS Capital Limited',
    'IHH Healthcare Berhad',
    'Inch Kenneth Kajang Rubber Public Ltd Company',
    'Indofood Agri Resources Ltd',
    'Informatics Education Ltd',
    'Innopac Holdings Limited',
    'InnoTek Limited',
    'International Cement Group Ltd',
    'Interra Resources Limited',
    'Intraco Limited',
    'IPC Corporation Limited',
    'IREIT Global',
    'ISDN Holdings Limited',
    'Isetan (Singapore) Limited',
    'Jackspeed Corporation Limited',
    'Jadason Enterprises Ltd',
    'Japfa Ltd',
    'Jardine Cycle & Carriage Limited',
    'Jardine Matheson Holdings Limited',
    'Jardine Strategic Holdings Limited',
    'Jasper Investments Limited',
    'JB Foods Limited',
    'JES International Holdings Limited',
    'Karin Technology Holdings Limited',
    'Kencana Agri Limited',
    'Keong Hong Holdings Limited',
    'Keppel Corporation Limited',
    'Keppel DC REIT',
    'Keppel Infrastructure Trust',
    'Keppel Pacific Oak US REIT',
    'Keppel REIT',
    'Khong Guan Limited',
    'King Wan Corporation Limited',
    'Kingsmen Creatives Ltd',
    'Koda Ltd',
    'Koh Brothers Group Limited',
    'Koon Holdings Limited',
    'Koufu Group Limited',
    'KrisEnergy Limited',
    'KS Energy Limited',
    'KSH Holdings Limited',
    'KTL Global Limited',
    'Lafe Corporation Limited',
    'Lantrovision (S) Ltd',
    'LCT Holdings Limited',
    'Leader Environmental Technologies Limited',
    'Lendlease Global Commercial REIT',
    'LHT Holdings Limited',
    'Lian Beng Group Limited',
    'Linc Energy Ltd',
    'Lion Asiapac Limited',
    'Lippo Malls Indo Retail Trust',
    'Lonza Group Ltd',
    'Lorenzo International Limited',
    'Low Keng Huat (Singapore) Limited',
    'Lum Chang Holdings Limited',
    'Lung Kee (Bermuda) Holdings Limited',
    'Luxking Group Holdings Limited',
    'Luzhou Bio-Chem Technology Limited',
    'M Development Ltd',
    'Malaysia Smelting Corp Bhd',
    'Mandarin Oriental Intl Ltd',
    'Manhattan Resources Limited',
    'Manufacturing Integration Technology Ltd',
    'Manulife US REIT',
    'Mapletree Commercial Trust',
    'Mapletree Industrial Trust',
    'Mapletree Logistics Trust',
    'Mapletree North Asia Commercial Trust',
    'Marco Polo Marine Ltd',
    'Maruwa Co Ltd',
    'mDR Limited',
    'Memstar Technology Ltd',
    'Mencast Holdings Ltd',
    'Mermaid Maritime Public Co Ltd',
    'Metro Holdings Limited',
    'Mewah International Inc',
    'Micro-Mechanics (Holdings) Ltd',
    'Midas Holdings Limited',
    'Mindchamps Preschool Limited',
    'Mirach Energy Limited',
    'mm2 Asia Ltd',
    'MMP Resources Limited',
    'MTQ Corporation Limited',
    'Multi-Chem Limited',
    'Mun Siong Engineering Limited',
    'MYP Ltd',
    'Nam Cheong Limited',
    'Nam Lee Pressed Metal Industries Limited',
    'Nanofilm Technologies International Limited',
    'Nera Telecommunications Ltd',
    'NetLink NBN Trust',
    'New Silkroutes Group Limited',
    'New Toyo International Holdings Ltd',
    'NGSC Limited',
    'Nico Steel Holdings Limited',
    'Nippecraft Limited',
    'Noble Group Limited',
    'Noel Gifts International Ltd',
    'Nordic Group Limited',
    'NSL Ltd',
    'Nutryfarm International Limited',
    'Oceanus Group Limited',
    'OKH Global Ltd',
    'OKP Holdings Limited',
    'Olam International Limited',
    'OneApex Limited',
    'Ossia International Limited',
    'OUE Commercial REIT',
    'OUE Limited',
    'Ouhua Energy Holdings Limited',
    'Oversea-Chinese Banking Corporation Limited',
    'Overseas Education Limited',
    'Oxley Holdings Limited',
    'Pacific Andes Resources Development Limited',
    'Pacific Century Regional Developments Limited',
    'Pacific Radiance Ltd',
    'Pan Hong Holdings Group Limited',
    'Pan Ocean Co, Ltd',
    'Pan-United Corporation Ltd',
    'Paragon REIT',
    'Parkson Retail Asia Limited',
    'Parkway Life REIT',
    'Pavillon Holdings Ltd',
    'PEC Ltd',
    'Penguin International Limited',
    'Perennial Real Estate Holdings Limited',
    'Pharmesis International Ltd',
    'Plastoform Holdings Limited',
    'PNE Industries Ltd',
    'Powermatic Data Systems Limited',
    'Prime US REIT',
    'Procurri Corporation Limited',
    'PropNex Limited',
    'Prudential plc',
    'PSL Holdings Limited',
    'PT Berlian Laju Tanker Tbk',
    'Q & M Dental Group (S) Limited',
    'QAF Limited',
    'Qian Hu Corporation Limited',
    'Raffles Education Corporation Limited',
    'Raffles Infrastructure Holdings Limited',
    'Raffles Medical Group Ltd',
    'Reenova Investment Holding Limited',
    'Regal International Group Ltd',
    'Renaissance United Limited',
    'Reyphon Agriceutical Limited',
    'RH PetroGas Limited',
    'RHT Health Trust',
    'Riverstone Holdings Limited',
    'Roxy-Pacific Holdings Limited',
    'Ryobi Kiso Holdings Ltd',
    "Sabana Shari'ah Compliant REIT",
    'Sakae Holdings Ltd',
    'Samko Timber Limited',
    'Samudera Shipping Line Ltd',
    'Sapphire Corporation Limited',
    'Sarine Technologies Ltd',
    'Sasseur REIT',
    'SATS',
    'SBS Transit',
    'Second Chance Properties Ltd',
    'Sembcorp Industries Ltd',
    'Sembcorp Marine Ltd',
    'Serial System Ltd',
    'Seroja Investments Limited',
    'Shanghai Turbo Enterprises Ltd',
    'Shangri-La Asia Limited',
    'Sheng Siong Group Ltd',
    'Shinvest Holding Ltd',
    'SHS Holdings Ltd',
    'SIA Engineering Company Limited',
    'SIIC Environment Holdings Ltd',
    'Silverlake Axis Ltd',
    'Sinarmas Land Limited',
    'Sin Ghee Huat Corporation Ltd',
    'Sin Heng Heavy Machinery Limited',
    'SingHaiyi Group Ltd',
    'Sing Holdings Limited',
    'Sing Investments & Finance Limited',
    'Singapore Airlines Limited',
    'Singapore Exchange Limited',
    'Singapore Myanmar Investco Limited',
    'Singapore Post Limited',
    'Singapore Reinsurance Corporation Limited',
    'Singapore Shipping Corporation Limited',
    'Singapore Technologies Engineering Ltd',
    'Singapura Finance Ltd',
    'Singapore Telecommunications Limited',
    'Sino Grandness Food Industry Group Limited',
    'Sinopipe Holdings Limited',
    'Sinostar Pec Holdings Limited',
    'Soilbuild Business Space REIT',
    'Soilbuild Construction Group Ltd',
    'Soup Restaurant Group Limited',
    'Southern Packaging Group Limited',
    'SP Corporation Limited',
    'Spindex Industries Limited',
    'Sri Trang Agro-Industry PCL',
    'Stamford Land Corporation Ltd',
    'Stamford Tyres Corporation Limited',
    'Starhill Global REIT',
    'StarHub Ltd',
    'Straco Corporation Limited',
    'The Straits Trading Company Limited',
    'Sunmoon Food Company Limited',
    'Sunningdale Tech Ltd',
    'Sunpower Group Ltd',
    'Sunright Limited',
    'Suntar Eco-City Limited',
    'Suntec Real Estate Investment Trust',
    'SunVic Chemical Holdings Limited',
    'SUTL Enterprise Limited',
    'Swee Hong Limited',
    'Swiber Holdings Limited',
    'Swing Media Technology Grp Ltd',
    'Swissco Holdings Limited',
    'TA Corporation Ltd',
    'Tai Sin Electric Limited',
    'Tat Seng Packaging Group Ltd',
    'Technics Oil & Gas Limited',
    'Teckwah Industrial Corporation Ltd',
    'TEE International Limited',
    'TeleChoice International Limited',
    'Thai Beverage Public Company Limited',
    'Thakral Corporation Ltd',
    'The Hour Glass Limited',
    'The Place Holdings Limited',
    'The Stratech Group Limited',
    'Thomson Medical Group Limited',
    'Tianjin Zhong Xin Pharm Group',
    'TIH Limited',
    'Tiong Seng Holdings Limited',
    'Tiong Woon Corporation Holding Ltd',
    'Top Global Limited',
    'Top Glove Corporation Bhd',
    'Tosei Corporation',
    'TOTM Technologies Limited',
    'Transit-Mixed Concrete Ltd',
    'Travelite Holdings Ltd',
    'Trek 2000 International Ltd',
    'TRIYARDS Holdings Limited',
    'TT International Limited',
    'TTJ Holdings Limited',
    'Tuan Sing Holdings Limited',
    'Tye Soon Limited',
    'UMS Holdings Limited',
    'Uni-Asia Group Limited',
]


def check_sgx_listed(entity_name):
    """
    Case-insensitive check of whether entity_name appears (exactly, or as a
    substring match in either direction) in the bundled SGX-listed companies
    reference list.

    Returns a dict:
      {"matched": bool, "matched_name": str or None}
    """
    if not entity_name:
        return {"matched": False, "matched_name": None}

    needle = entity_name.strip().lower()
    for name in SGX_LISTED_COMPANIES:
        hay = name.strip().lower()
        if needle == hay or needle in hay or hay in needle:
            return {"matched": True, "matched_name": name}
    return {"matched": False, "matched_name": None}
